<!doctype html>
<html lang="nl"><head><meta charset="utf-8"><style>
@page{margin:28px 30px 38px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:9px;line-height:1.35}h1{font-size:22px;margin:0;color:#173a8a}h2{font-size:14px;margin:20px 0 7px;color:#172033}h3{font-size:11px;margin:13px 0 5px}.muted{color:#64748b}.header{border-bottom:2px solid #2563eb;padding-bottom:12px}.meta{width:100%;margin-top:10px;border-collapse:collapse}.meta td{padding:2px 8px 2px 0}.cards{width:100%;margin:12px 0;border-spacing:5px}.card{background:#f1f5f9;padding:8px}.value{font-size:16px;font-weight:bold}.label{font-size:8px;color:#64748b;text-transform:uppercase}table.data{width:100%;border-collapse:collapse}table.data th{background:#eaf1ff;text-align:left;padding:5px;border-bottom:1px solid #cbd5e1}table.data td{padding:5px;border-bottom:1px solid #e2e8f0;vertical-align:top}.status{font-weight:bold}.danger{color:#b91c1c}.ok{color:#047857}.page-break{page-break-before:always}.task{margin:4px 0;padding:6px;background:#f8fafc;border-left:3px solid #cbd5e1;page-break-inside:avoid}.task.deviation{background:#fff7ed;border-left-color:#ea580c}.proof{margin:5px 5px 5px 0;max-width:150px;max-height:110px}.signature{max-width:145px;max-height:65px;border:1px solid #cbd5e1;padding:3px}.audit{border-left:2px solid #2563eb;padding-left:8px;margin:5px 0}.footer{position:fixed;bottom:-24px;left:0;right:0;font-size:8px;color:#64748b;border-top:1px solid #e2e8f0;padding-top:5px}.badge{display:inline-block;padding:2px 5px;background:#e2e8f0}.declaration{margin-top:15px;padding:9px;border:1px solid #cbd5e1;background:#f8fafc}
</style></head><body>
<div class="footer">{{ $company->name }} · {{ $reportNumber }} · gegenereerd {{ now()->format('d-m-Y H:i') }}</div>
<div class="header"><h1>HACCP-uitvoeringsrapport</h1><div><strong>{{ $list->title }}</strong></div>
<table class="meta"><tr><td><strong>Bedrijf:</strong> {{ $company->name }}</td><td><strong>Rapportnummer:</strong> {{ $reportNumber }}</td></tr>
<tr><td><strong>Vestiging:</strong> {{ $list->location?->name ?? 'Alle locaties / algemeen' }}@if($list->location?->address) — {{ $list->location->address }}@endif</td><td><strong>Generatiedatum:</strong> {{ now()->format('d-m-Y H:i') }}</td></tr>
<tr><td><strong>Rapportageperiode:</strong> {{ $start->format('d-m-Y') }} t/m {{ $end->format('d-m-Y') }}</td><td><strong>Verantwoordelijke beoordelaar(s):</strong> {{ $reviewers->isNotEmpty() ? $reviewers->join(', ') : 'Niet geregistreerd' }}</td></tr></table></div>

<table class="cards"><tr>
<td class="card"><div class="value">{{ $summary['total'] }}</div><div class="label">Uitvoeringen</div></td><td class="card"><div class="value">{{ $summary['completion_rate'] }}%</div><div class="label">Afgerond</div></td><td class="card"><div class="value">{{ $summary['tasks_completed'] }}/{{ $summary['tasks_total'] }}</div><div class="label">Taken voltooid</div></td><td class="card"><div class="value {{ $summary['deviations'] ? 'danger' : 'ok' }}">{{ $summary['deviations'] }}</div><div class="label">Afwijkingen</div></td>
</tr></table>

<h2>Uitvoering over tijd</h2><table class="data"><thead><tr><th>Datum</th><th>Uitgevoerd</th><th>Afgerond</th><th>Percentage</th></tr></thead><tbody>
@forelse($trend as $day)<tr><td>{{ $day['date']->format('d-m-Y') }}</td><td>{{ $day['total'] }}</td><td>{{ $day['finished'] }}</td><td>{{ $day['total'] ? round($day['finished']/$day['total']*100) : 0 }}%</td></tr>@empty<tr><td colspan="4">Geen uitvoeringen in deze periode.</td></tr>@endforelse</tbody></table>

<h2>Afwijkingen en corrigerende maatregelen</h2><table class="data"><thead><tr><th>Datum / controlepunt</th><th>Afwijking</th><th>Corrigerende maatregel</th><th>Opvolging</th></tr></thead><tbody>
@forelse($deviations as $task)<tr><td>{{ optional($task->completed_at ?? $task->created_at)->format('d-m-Y H:i') }}<br><strong>{{ $task->task?->title }}</strong></td><td>{{ $task->rejection_reason ?: ($task->proof_text ?: 'Afwijkende status geregistreerd') }}</td><td>{{ $task->redo_reason ?: ($task->manager_comment ?: 'Geen afzonderlijke maatregel geregistreerd') }}</td><td>{{ $task->redo_requested ? 'Opnieuw uitvoeren gevraagd' : ($task->status === 'approved' ? 'Goedgekeurd na opvolging' : ucfirst(str_replace('_',' ',$task->status))) }}@if($task->reviewer)<br>door {{ $task->reviewer->name }}@endif</td></tr>@empty<tr><td colspan="4" class="ok">Geen geregistreerde afwijkingen in deze periode.</td></tr>@endforelse</tbody></table>

<h2>Inzendingen</h2><table class="data"><thead><tr><th>ID / datum</th><th>Uitvoerder</th><th>Status</th><th>Voortgang</th><th>Beoordelaar</th></tr></thead><tbody>
@foreach($submissions as $submission) @php($done=$submission->submissionTasks->whereIn('status',['completed','approved'])->count())
<tr><td>#{{ $submission->id }}<br>{{ $submission->created_at->format('d-m-Y H:i') }}</td><td>{{ $submission->user?->name ?? 'Onbekend' }}</td><td class="status">{{ ucfirst(str_replace('_',' ',$submission->status)) }}</td><td>{{ $submission->submissionTasks->count() ? round($done/$submission->submissionTasks->count()*100) : 0 }}%</td><td>{{ $submission->submissionTasks->pluck('reviewer.name')->filter()->unique()->join(', ') ?: '—' }}</td></tr>@endforeach</tbody></table>

@if($submissions->isNotEmpty())<div class="page-break"></div><h2>Controlepunten, bewijs en ondertekening</h2>@endif
@foreach($submissions as $submission)
<h3>Inzending #{{ $submission->id }} · {{ $submission->created_at->format('d-m-Y H:i') }} · {{ $submission->user?->name ?? 'Onbekend' }}</h3>
@foreach($submission->submissionTasks as $task)
@php($isDeviation=in_array($task->status,['rejected','redo_requested'],true)||$task->rejection_reason||$task->redo_reason)
<div class="task {{ $isDeviation ? 'deviation' : '' }}"><strong>{{ $task->task?->title }}</strong> <span class="badge">{{ $task->status }}</span>
@if($task->proof_text)<br><strong>Waarde/antwoord:</strong> {{ $task->proof_text }}@endif @if($task->employee_comment)<br><strong>Opmerking uitvoerder:</strong> {{ $task->employee_comment }}@endif
@if($task->manager_comment)<br><strong>Beoordeling:</strong> {{ $task->manager_comment }}@endif @if($task->rejection_reason)<br><strong>Afwijking:</strong> {{ $task->rejection_reason }}@endif @if($task->redo_reason)<br><strong>Corrigerende maatregel:</strong> {{ $task->redo_reason }}@endif
@foreach(($task->proof_files ?? []) as $file) @php($path=is_array($file)?($file['path']??null):$file) @php($mime=is_array($file)?($file['mime_type']??''):'')
@if($path && (str_starts_with($mime,'image/') || preg_match('/\.(jpe?g|png|webp)$/i',$path)) && file_exists(public_path('storage/'.$path)))<br><img class="proof" src="{{ public_path('storage/'.$path) }}" alt="Bewijsfoto">@elseif($path)<br><span class="muted">Bijlage: {{ basename($path) }}</span>@endif @endforeach
@if($task->digital_signature)<br><strong>Taak ondertekend:</strong><br><img class="signature" src="{{ $task->digital_signature }}" alt="Taakhandtekening">@endif
</div>@endforeach
<h3>Audittrail inzending #{{ $submission->id }}</h3><div class="audit">Aangemaakt: {{ optional($submission->created_at)->format('d-m-Y H:i') }}<br>Gestart: {{ optional($submission->started_at)->format('d-m-Y H:i') ?: 'Niet geregistreerd' }}<br>Afgerond: {{ optional($submission->completed_at)->format('d-m-Y H:i') ?: 'Niet geregistreerd' }}<br>Beoordeeld: {{ optional($submission->submissionTasks->max('reviewed_at'))->format('d-m-Y H:i') ?: 'Niet geregistreerd' }}<br>Herstelverzoeken: {{ $submission->submissionTasks->where('redo_requested',true)->count() }}</div>
@if($submission->employee_signature || $submission->manager_signature)<table class="meta"><tr><td><strong>Handtekening medewerker</strong><br>@if($submission->employee_signature)<img class="signature" src="{{ $submission->employee_signature }}">@else Niet aanwezig @endif</td><td><strong>Handtekening beoordelaar</strong><br>@if($submission->manager_signature)<img class="signature" src="{{ $submission->manager_signature }}">@else Niet aanwezig @endif</td></tr></table>@endif
@endforeach
<div class="declaration"><strong>Verklaring rapportage</strong><br>Dit rapport is automatisch samengesteld uit de in TaskCheck geregistreerde uitvoeringen, bewijsstukken, beoordelingen en tijdstempels. Ontbrekende gegevens worden expliciet als niet geregistreerd weergegeven.</div>
</body></html>
