<!doctype html><html lang="nl"><head><meta charset="utf-8"><style>
@page{margin:30px 34px 42px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:9px;line-height:1.35}h1{font-size:21px;margin:0;color:#163c8c}h2{font-size:13px;margin:18px 0 7px;padding-bottom:4px;border-bottom:1px solid #cbd5e1}h3{font-size:10px;margin:11px 0 4px}.muted{color:#64748b}.small{font-size:8px}.header{border-bottom:3px solid #2563eb;padding-bottom:12px}.meta,.data,.cards{width:100%;border-collapse:collapse}.meta{margin-top:9px}.meta td{padding:2px 10px 2px 0}.cards{margin:12px 0;border-spacing:5px;border-collapse:separate}.card{background:#eff6ff;padding:8px}.card.warn{background:#fff7ed}.card.danger{background:#fef2f2}.value{font-size:16px;font-weight:bold}.label{font-size:7px;color:#64748b;text-transform:uppercase}.data th{background:#eaf1ff;text-align:left;padding:5px;border-bottom:1px solid #94a3b8}.data td{padding:5px;border-bottom:1px solid #e2e8f0;vertical-align:top}.ok{color:#047857}.warn-text{color:#b45309}.danger-text{color:#b91c1c}.badge{display:inline-block;padding:2px 5px;background:#e2e8f0;font-size:8px}.badge.ok{background:#d1fae5}.badge.warn{background:#ffedd5}.badge.danger{background:#fee2e2}.page-break{page-break-before:always}.avoid{page-break-inside:avoid}.evidence{display:inline-block;width:145px;vertical-align:top;margin:4px 7px 8px 0}.evidence img{max-width:145px;max-height:105px;border:1px solid #cbd5e1}.signature{max-width:135px;max-height:55px;border:1px solid #cbd5e1;padding:2px}.notice{padding:8px;background:#f8fafc;border:1px solid #cbd5e1}.footer{position:fixed;bottom:-27px;left:0;right:0;border-top:1px solid #e2e8f0;padding-top:5px;color:#64748b;font-size:7px}.timeline{border-left:2px solid #2563eb;padding-left:7px}.finding{border-left:3px solid #ea580c;background:#fff7ed;padding:7px;margin:5px 0}.check{margin-bottom:10px}.check-title{font-weight:bold}.nowrap{white-space:nowrap}
</style></head><body>
@php
$statusLabel=['pending'=>'Open','in_progress'=>'Bezig','completed'=>'Uitgevoerd','approved'=>'Goedgekeurd','reviewed'=>'Beoordeeld','rejected'=>'Afgekeurd','redo_requested'=>'Opnieuw uitvoeren'];
$resultFor=function($submission) { if($submission->submissionTasks->contains(fn($t)=>in_array($t->status,['pending','rejected','redo_requested'],true))) return ['Aandacht nodig','danger']; if($submission->submissionTasks->isNotEmpty() && $submission->submissionTasks->every(fn($t)=>in_array($t->status,['completed','approved'],true))) return ['Volledig geregistreerd','ok']; return ['Onvolledig','warn']; };
@endphp
<div class="footer">{{ $company->name }} · {{ $reportNumber }} · interne zelfcontroleregistratie · {{ now()->format('d-m-Y H:i') }}</div>
<div class="header"><h1>Perioderapport interne voedselveiligheidscontroles</h1><div><strong>{{ $list->title }}</strong></div>
<table class="meta"><tr><td><strong>Organisatie</strong><br>{{ $company->name }}</td><td><strong>Vestiging</strong><br>{{ $list->location?->name ?? 'Algemeen' }}@if($list->location?->address), {{ $list->location->address }}@endif</td><td><strong>Rapportnummer</strong><br>{{ $reportNumber }}</td></tr><tr><td><strong>Periode</strong><br>{{ $start->format('d-m-Y') }} t/m {{ $end->format('d-m-Y') }}</td><td><strong>Hygiënecode</strong><br>{{ $list->hygiene_code ?: 'Niet gekoppeld' }}</td><td><strong>HACCP-plan</strong><br>{{ $list->haccp_plan_reference ?: 'Niet gekoppeld' }}</td></tr><tr><td><strong>Beoordelaar(s)</strong><br>{{ $reviewers->join(', ') ?: 'Niet geregistreerd' }}</td><td colspan="2"><strong>Gegenereerd</strong><br>{{ now()->format('d-m-Y H:i') }}</td></tr></table></div>

<div class="notice" style="margin-top:10px"><strong>Doel en reikwijdte</strong><br>Dit rapport bundelt interne uitvoerings- en zelfcontrolegegevens uit TaskCheck. Het laat zien welke controles zijn geregistreerd, waar opvolging nodig is en welk bewijs is vastgelegd. Het is geen onafhankelijk inspectieoordeel, HACCP-certificaat of verklaring dat aan een specifieke hygiënecode is voldaan. De toepasselijke hygiënecode/HACCP-norm is alleen aantoonbaar wanneer die aan de controlepunten zelf is gekoppeld.</div>

<h2>1. Managementsamenvatting</h2><table class="cards"><tr>
<td class="card"><div class="value">{{ $summary['expected'] }}</div><div class="label">Verwacht volgens planning</div></td><td class="card"><div class="value">{{ $summary['finished'] }}</div><div class="label">Volledig uitgevoerd</div></td><td class="card warn"><div class="value">{{ $summary['coverage_rate'] === null ? 'n.v.t.' : $summary['coverage_rate'].'%' }}</div><div class="label">Dekkingsgraad</div></td><td class="card danger"><div class="value">{{ $summary['open_deviations'] }}</div><div class="label">Open bevindingen</div></td><td class="card"><div class="value">{{ $summary['closed_deviations'] }}</div><div class="label">Geverifieerd gesloten</div></td>
</tr></table>
<p><strong>Interpretatie:</strong> {{ $summary['finished'] }} van {{ $summary['expected'] }} geplande controlemomenten zijn volledig geregistreerd. Er zijn daarnaast {{ $summary['incomplete'] }} aangemaakte maar onvolledige registraties. De verwachting is afgeleid van het planningsschema van de takenlijst.</p>

<h2>2. Controlehistorie</h2><table class="data"><thead><tr><th>Datum</th><th>Uitvoerder</th><th>Registratieresultaat</th><th>Taken</th><th>Open punten</th><th>Beoordeling</th></tr></thead><tbody>
@forelse($submissions as $submission) @php([$result,$tone]=$resultFor($submission)) @php($done=$submission->submissionTasks->whereIn('status',['completed','approved'])->count()) @php($open=$submission->submissionTasks->filter(fn($t)=>in_array($t->status,['pending','rejected','redo_requested'],true))->count())
<tr><td class="nowrap">{{ $submission->created_at->format('d-m-Y H:i') }}</td><td>{{ $submission->user?->name ?? 'Onbekend' }}</td><td><span class="badge {{ $tone }}">{{ $result }}</span></td><td>{{ $done }}/{{ $submission->submissionTasks->count() }}</td><td>{{ $open }}</td><td>{{ $submission->submissionTasks->pluck('reviewer.name')->filter()->unique()->join(', ') ?: 'Niet geregistreerd' }}</td></tr>
@empty<tr><td colspan="6">Geen registraties gevonden in deze periode.</td></tr>@endforelse</tbody></table>

<h2>3. Bevindingen- en verbeterregister</h2><table class="data"><thead><tr><th>Datum / controlepunt</th><th>Feitelijke bevinding</th><th>Actie / eigenaar / termijn</th><th>Verificatie en sluiting</th></tr></thead><tbody>
@forelse($deviations as $task)<tr><td>{{ optional($task->completed_at ?? $task->created_at)->format('d-m-Y H:i') }}<br><strong>{{ $task->task?->title }}</strong><br><span class="small muted">Norm: {{ $task->task?->norm_reference ?: 'niet gekoppeld' }}</span></td><td>{{ $task->rejection_reason ?: ($task->employee_comment ?: ($task->proof_text ?: 'Controlepunt niet volledig afgerond')) }}</td><td><strong>Actie:</strong> {{ $task->corrective_action ?: ($task->redo_reason ?: 'Niet geregistreerd') }}<br><strong>Eigenaar:</strong> {{ $task->correctiveActionOwner?->name ?: 'Niet toegewezen' }}<br><strong>Termijn:</strong> {{ optional($task->corrective_action_due_at)->format('d-m-Y') ?: 'Niet geregistreerd' }}</td><td><strong>Status:</strong> {{ $task->verified_at ? 'Geverifieerd gesloten' : 'Open' }}<br><strong>Verificatie:</strong> {{ $task->verification_note ?: 'Niet geregistreerd' }}<br><strong>Door:</strong> {{ $task->verifier?->name ?: 'Niet geregistreerd' }}<br><strong>Datum:</strong> {{ optional($task->verified_at)->format('d-m-Y H:i') ?: 'Niet geregistreerd' }}</td></tr>
@empty<tr><td colspan="4" class="ok">Geen openstaande of geregistreerde afwijkingen aangetroffen.</td></tr>@endforelse</tbody></table>

@if($submissions->isNotEmpty())<div class="page-break"></div>@endif
<h2>4. Detailregistraties</h2>
@foreach($submissions as $submission) @php([$result,$tone]=$resultFor($submission))
<div class="check avoid"><h3>Registratie #{{ $submission->id }} · {{ $submission->created_at->format('d-m-Y H:i') }} · {{ $submission->user?->name ?? 'Onbekend' }} · <span class="{{ $tone === 'ok' ? 'ok' : ($tone === 'danger' ? 'danger-text' : 'warn-text') }}">{{ $result }}</span></h3>
<table class="data"><thead><tr><th>Controlepunt</th><th>Resultaat / meting</th><th>Status</th><th>Opmerking</th></tr></thead><tbody>
@foreach($submission->submissionTasks as $task)<tr><td>{{ $task->task?->title }}@if($task->task?->norm_reference)<br><span class="small muted">{{ $task->task->norm_reference }}</span>@endif</td><td>{{ $task->proof_text ?: '—' }}@if($task->checklist_progress)<br><span class="small muted">{{ json_encode($task->checklist_progress, JSON_UNESCAPED_UNICODE) }}</span>@endif</td><td>{{ $statusLabel[$task->status] ?? $task->status }}</td><td>{{ $task->employee_comment ?: ($task->manager_comment ?: '—') }}</td></tr>@endforeach</tbody></table>
<div class="timeline small"><strong>Audittrail:</strong> aangemaakt {{ optional($submission->created_at)->format('d-m-Y H:i') }} · gestart {{ optional($submission->started_at)->format('d-m-Y H:i') ?: 'n.g.' }} · afgerond {{ optional($submission->completed_at)->format('d-m-Y H:i') ?: 'n.g.' }} · laatste beoordeling {{ optional($submission->submissionTasks->max('reviewed_at'))->format('d-m-Y H:i') ?: 'n.g.' }}</div></div>
@endforeach

@if($deviations->contains(fn($task)=>!empty($task->proof_files)))<div class="page-break"></div><h2>5. Bewijs bij bevindingen</h2>
@foreach($deviations as $task) @if(!empty($task->proof_files))<div class="avoid"><h3>{{ $task->task?->title }} · {{ optional($task->completed_at)->format('d-m-Y H:i') }}</h3>
@foreach($task->proof_files as $file) @php($path=is_array($file)?($file['path']??null):$file) @php($mime=is_array($file)?($file['mime_type']??''):'')
<div class="evidence">@if($path && (str_starts_with($mime,'image/')||preg_match('/\.(jpe?g|png|webp)$/i',$path)) && file_exists(public_path('storage/'.$path)))<img src="{{ public_path('storage/'.$path) }}" alt="Bewijs"><br>@endif<span class="small">{{ $path ? basename($path) : 'Bijlage' }}</span></div>@endforeach</div>@endif @endforeach @endif

<h2>6. Ondertekening en herleidbaarheid</h2><p>Digitale handtekeningen en bewijsbestanden blijven gekoppeld aan de oorspronkelijke inzending. Onderstaande aanwezigheid is per registratie vastgelegd.</p><table class="data"><thead><tr><th>Inzending</th><th>Medewerker</th><th>Beoordelaar</th><th>Handtekening medewerker</th><th>Handtekening manager</th></tr></thead><tbody>
@foreach($submissions as $submission)<tr><td>#{{ $submission->id }}</td><td>{{ $submission->user?->name }}</td><td>{{ $submission->submissionTasks->pluck('reviewer.name')->filter()->unique()->join(', ') ?: '—' }}</td><td>{{ $submission->employee_signature ? 'Aanwezig' : 'Niet aanwezig' }}</td><td>{{ $submission->manager_signature ? 'Aanwezig' : 'Niet aanwezig' }}</td></tr>@endforeach</tbody></table>
</body></html>
