<div class="mx-auto max-w-4xl space-y-6">
    <div><h2 class="text-xl font-bold text-slate-900">Microsoft Entra ID & SCIM</h2><p class="mt-1 text-sm text-slate-500">Beheer SSO, MFA, groepsrollen en gebruikersprovisioning voor {{ $company->name }}.</p></div>

    @if(session('scim_token'))<div class="rounded-2xl border border-amber-300 bg-amber-50 p-4"><p class="font-semibold text-amber-900">Eenmalig zichtbare SCIM-token</p><code class="mt-2 block break-all rounded-xl bg-white p-3 text-sm">{{ session('scim_token') }}</code></div>@endif
    @if($errors->any())<div class="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <form method="POST" action="{{ route('super-admin.companies.identity.update', $company) }}" class="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">@csrf @method('PUT')
        <div class="grid gap-3 sm:grid-cols-3">
            @foreach(['entra_enabled' => ['Entra SSO actief','Microsoft-aanmelding toestaan.'], 'entra_mfa_required' => ['MFA-claim verplicht','Entra moet MFA bevestigen.'], 'entra_sso_required' => ['Lokale login blokkeren','Alleen Microsoft-login toestaan.']] as $name => [$label, $description])
                <label class="flex items-start gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" name="{{ $name }}" value="1" class="mt-0.5 rounded border-slate-300 text-blue-600" @checked(old($name, $company->$name))><span><strong class="block text-sm text-slate-900">{{ $label }}</strong><span class="mt-0.5 block text-xs text-slate-500">{{ $description }}</span></span></label>
            @endforeach
        </div>
        <div class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><strong>Veilige volgorde:</strong> configureer Entra, test een Microsoft-login en schakel pas daarna “Lokale login blokkeren” in.</div>
        <div><label class="block text-sm font-semibold text-slate-700">Zakelijk e-maildomein</label><input name="domain" required value="{{ old('domain', $company->domain) }}" placeholder="bedrijf.nl" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"></div>
        <div class="grid gap-4 sm:grid-cols-2"><div><label class="block text-sm font-semibold text-slate-700">Tenant ID</label><input name="entra_tenant_id" value="{{ old('entra_tenant_id', $company->entra_tenant_id) }}" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"></div><div><label class="block text-sm font-semibold text-slate-700">Client ID</label><input name="entra_client_id" value="{{ old('entra_client_id', $company->entra_client_id) }}" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"></div></div>
        <div><label class="block text-sm font-semibold text-slate-700">Client secret</label><input type="password" name="entra_client_secret" autocomplete="new-password" placeholder="Leeg laten om bestaand secret te behouden" class="mt-1 block w-full rounded-xl border-slate-300 text-sm"></div>
        <div><label class="block text-sm font-semibold text-slate-700">Admin-groeps-ID's</label><textarea name="entra_admin_group_ids" rows="2" class="mt-1 block w-full rounded-xl border-slate-300 text-sm" placeholder="GUID's, gescheiden door komma's">{{ old('entra_admin_group_ids', implode(', ', $company->entra_admin_group_ids ?? [])) }}</textarea></div>
        <div><label class="block text-sm font-semibold text-slate-700">Medewerker-groeps-ID's</label><textarea name="entra_employee_group_ids" rows="2" class="mt-1 block w-full rounded-xl border-slate-300 text-sm">{{ old('entra_employee_group_ids', implode(', ', $company->entra_employee_group_ids ?? [])) }}</textarea></div>
        <p class="text-xs text-slate-500">Redirect URI: <code class="rounded bg-slate-100 px-1.5 py-0.5">{{ route('entra.callback') }}</code></p>
        <div class="flex justify-end"><button class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">SSO-instellingen opslaan</button></div>
    </form>

    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 class="font-semibold text-slate-900">SCIM 2.0-provisioning</h3><p class="mt-1 text-sm text-slate-500">Laat Microsoft gebruikers automatisch aanmaken en deactiveren.</p>@if($company->scim_endpoint_key)<p class="mt-4 text-xs font-semibold uppercase tracking-wide text-slate-500">Tenant URL</p><code class="mt-1 block break-all rounded-xl bg-slate-50 p-3 text-sm">{{ url('/api/scim/v2/'.$company->scim_endpoint_key) }}</code>@endif<form method="POST" action="{{ route('super-admin.companies.identity.scim-token', $company) }}" class="mt-4">@csrf<button class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ $company->scim_token_hash ? 'SCIM-token roteren' : 'SCIM-token aanmaken' }}</button></form></section>
</div>
