<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
    <div class="flex items-center justify-between gap-3"><div><h2 class="font-semibold text-slate-900">Abonnement beheren</h2><p class="text-xs text-slate-500">Plan, toegang en facturatie.</p></div><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 {{ $statusStyles }}">{{ $statusLabel }}</span></div>
    <form method="POST" action="{{ route('super-admin.companies.subscription.update', $company) }}" class="mt-5 space-y-4">@csrf @method('PUT')
        <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Abonnement</label><select id="subscription-plan" name="subscription_plan" class="w-full rounded-xl border-slate-300 text-sm focus:border-blue-500 focus:ring-blue-500">@foreach(\App\Models\Organisation\Company::PLANS as $planKey => $planData)<option value="{{ $planKey }}" @selected(old('subscription_plan', $company->subscription_plan) === $planKey)>{{ $planData['name'] }}</option>@endforeach</select></div>
        <div id="custom-subscription-fields" class="space-y-3 rounded-xl border border-blue-200 bg-blue-50 p-3">
            <p class="text-sm font-semibold text-slate-900">Klant-specifiek abonnement</p>
            <div><label class="mb-1 block text-xs font-medium text-slate-700">Naam</label><input name="custom_subscription_name" value="{{ old('custom_subscription_name', $company->custom_subscription_name) }}" placeholder="Bijv. Kwalitaria Plus" class="w-full rounded-lg border-slate-300 text-sm">@error('custom_subscription_name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div><label class="mb-1 block text-xs font-medium text-slate-700">Prijs per maand (excl. btw)</label><input name="custom_monthly_price" type="number" min="0" step="0.01" value="{{ old('custom_monthly_price', $company->custom_monthly_price) }}" class="w-full rounded-lg border-slate-300 text-sm">@error('custom_monthly_price')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
            <div class="grid grid-cols-3 gap-2">
                <div><label class="mb-1 block text-xs font-medium text-slate-700">Gebruikers</label><input name="custom_max_users" type="number" min="-1" value="{{ old('custom_max_users', $company->max_users ?? -1) }}" class="w-full rounded-lg border-slate-300 text-sm"></div>
                <div><label class="mb-1 block text-xs font-medium text-slate-700">Locaties</label><input name="custom_max_locations" type="number" min="-1" value="{{ old('custom_max_locations', $company->max_locations ?? -1) }}" class="w-full rounded-lg border-slate-300 text-sm"></div>
                <div><label class="mb-1 block text-xs font-medium text-slate-700">Opslag GB</label><input name="custom_max_storage_gb" type="number" min="-1" value="{{ old('custom_max_storage_gb', $company->max_storage_gb ?? -1) }}" class="w-full rounded-lg border-slate-300 text-sm"></div>
            </div>
            <p class="text-[11px] text-slate-500">Gebruik -1 voor onbeperkt.</p>
        </div>
        <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Abonnementsstatus</label><select name="subscription_status" class="w-full rounded-xl border-slate-300 text-sm focus:border-blue-500 focus:ring-blue-500">@foreach(['trial' => 'Proefperiode', 'active' => 'Actief', 'cancelled' => 'Geannuleerd', 'expired' => 'Verlopen'] as $value => $label)<option value="{{ $value }}" @selected(old('subscription_status', $status) === $value)>{{ $label }}</option>@endforeach</select></div>
        <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Einddatum gratis toegang</label><input type="date" name="subscription_ends_at" value="{{ old('subscription_ends_at', optional($company->subscription_ends_at)->format('Y-m-d')) }}" class="w-full rounded-xl border-slate-300 text-sm focus:border-blue-500 focus:ring-blue-500"><p class="mt-1 text-xs text-slate-500">Verplicht bij gratis toegang. Een ingevulde datum wordt ook bij maandelijkse betaling bewaard.</p>@error('subscription_ends_at')<p class="mt-1 text-xs font-medium text-red-600">{{ $message }}</p>@enderror</div>
        <div class="space-y-2 rounded-xl border border-slate-200 bg-slate-50 p-3"><label class="flex items-start gap-2 text-sm text-slate-700"><input type="checkbox" name="billing_required" value="1" class="mt-0.5 rounded border-slate-300 text-blue-600" @checked(old('billing_required', $company->billing_required))><span><strong class="font-medium text-slate-900">Maandelijkse betaling</strong><br><span class="text-xs text-slate-500">Facturatie en abonnement blijven doorlopen.</span></span></label><label class="flex items-start gap-2 border-t border-slate-200 pt-2 text-sm text-slate-700"><input type="checkbox" name="is_active" value="1" class="mt-0.5 rounded border-slate-300 text-blue-600" @checked(old('is_active', $company->is_active))><span><strong class="font-medium text-slate-900">Platformtoegang actief</strong><br><span class="text-xs text-slate-500">Gebruikers van dit bedrijf kunnen inloggen.</span></span></label></div>
        <button type="submit" class="w-full rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-blue-700">Wijzigingen opslaan</button>
    </form>
</section>
