<dialog id="edit-company-user-{{ $dialogUser->id }}" class="w-[calc(100%-2rem)] max-w-xl rounded-2xl p-0 shadow-2xl backdrop:bg-slate-950/50">
    <form method="POST" action="{{ route('super-admin.companies.users.update', [$company, $dialogUser]) }}">@csrf @method('PUT')
        <div class="flex items-start justify-between border-b border-slate-100 px-5 py-4"><div><h3 class="text-lg font-semibold text-slate-900">{{ $dialogUser->name }} bewerken</h3><p class="mt-0.5 text-sm text-slate-500">Pas accountgegevens, rol en locatie aan.</p></div><button type="button" data-close-dialog class="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Sluiten">✕</button></div>
        <div class="grid gap-4 p-5 sm:grid-cols-2">
            <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Naam</label><input name="name" value="{{ $dialogUser->name }}" required class="w-full rounded-xl border-slate-300 text-sm focus:border-blue-500 focus:ring-blue-500"></div>
            <div><label class="mb-1.5 block text-sm font-medium text-slate-700">E-mailadres</label><input name="email" type="email" value="{{ $dialogUser->email }}" required class="w-full rounded-xl border-slate-300 text-sm focus:border-blue-500 focus:ring-blue-500"></div>
            <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Rol</label><select name="role" required class="w-full rounded-xl border-slate-300 text-sm"><option value="admin" @selected($dialogUser->role === 'admin')>Beheerder</option><option value="employee" @selected($dialogUser->role === 'employee') @disabled($dialogUser->is(auth()->user()))>Medewerker</option></select>@if($dialogUser->is(auth()->user()))<p class="mt-1 text-xs text-slate-500">Je eigen superadminrol blijft beheerder.</p>@endif</div>
            <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Locatie</label><select name="location_id" class="w-full rounded-xl border-slate-300 text-sm"><option value="">Alle locaties</option>@foreach($companyLocations as $location)<option value="{{ $location->id }}" @selected((int)$dialogUser->location_id === (int)$location->id)>{{ $location->name }}</option>@endforeach</select></div>
            <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Telefoon <span class="font-normal text-slate-400">(optioneel)</span></label><input name="phone" value="{{ $dialogUser->phone }}" class="w-full rounded-xl border-slate-300 text-sm"></div>
            <div><label class="mb-1.5 block text-sm font-medium text-slate-700">Nieuw wachtwoord <span class="font-normal text-slate-400">(optioneel)</span></label><input name="password" type="password" minlength="12" autocomplete="new-password" class="w-full rounded-xl border-slate-300 text-sm"><p class="mt-1 text-xs text-slate-500">Leeg laten om niet te wijzigen.</p></div>
        </div>
        <div class="flex justify-end gap-3 border-t border-slate-100 bg-slate-50 px-5 py-4"><button type="button" data-close-dialog class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700">Annuleren</button><button class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Wijzigingen opslaan</button></div>
    </form>
</dialog>
