@php($recipient = (array) $recipient)
<article class="report-recipient rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
    @if(!empty($recipient['id']))<input type="hidden" name="report_recipients[{{ $index }}][id]" value="{{ $recipient['id'] }}">@endif
    <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-6">
        <div class="xl:col-span-2"><label class="block text-xs font-semibold text-slate-600">E-mailadres</label><input type="email" required name="report_recipients[{{ $index }}][email]" value="{{ $recipient['email'] ?? '' }}" class="mt-1 w-full rounded-lg border-slate-300 text-sm" placeholder="naam@bedrijf.nl"></div>
        <div><label class="block text-xs font-semibold text-slate-600">Frequentie</label><select name="report_recipients[{{ $index }}][frequency]" class="report-frequency mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="daily" @selected(($recipient['frequency'] ?? '') === 'daily')>Dagelijks</option><option value="weekly" @selected(($recipient['frequency'] ?? '') === 'weekly')>Wekelijks</option></select></div>
        <div class="report-weekday"><label class="block text-xs font-semibold text-slate-600">Verzenddag</label><select name="report_recipients[{{ $index }}][weekly_day]" class="mt-1 w-full rounded-lg border-slate-300 text-sm">@foreach(\App\Models\Organisation\Company::WEEKDAYS as $dayKey => $dayLabel)<option value="{{ $loop->iteration }}" @selected((int)($recipient['weekly_day'] ?? 1) === $loop->iteration)>{{ $dayLabel }}</option>@endforeach</select></div>
        <div><label class="block text-xs font-semibold text-slate-600">Tijdstip</label><input type="time" required name="report_recipients[{{ $index }}][send_time]" value="{{ $recipient['send_time'] ?? '18:00' }}" class="mt-1 w-full rounded-lg border-slate-300 text-sm"></div>
        <div><label class="block text-xs font-semibold text-slate-600">Ontvangst</label><select name="report_recipients[{{ $index }}][delivery_format]" class="mt-1 w-full rounded-lg border-slate-300 text-sm"><option value="email" @selected(($recipient['delivery_format'] ?? '') === 'email')>Opgemaakte e-mail</option><option value="pdf" @selected(($recipient['delivery_format'] ?? '') === 'pdf')>PDF-bijlage</option><option value="both" @selected(($recipient['delivery_format'] ?? 'both') === 'both')>E-mail + PDF</option></select></div>
    </div>
    <div class="mt-3 flex items-center justify-between"><p class="text-xs text-slate-500">Tijdzone: Nederland (Europe/Amsterdam)</p><button type="button" class="remove-report-recipient text-xs font-semibold text-red-600 hover:text-red-800">Ontvanger verwijderen</button></div>
</article>
